[2025-07-24 18:44:16,768] INFO django.request: GET / | Status: 200 | User: Anonymous | Duration: 97.43 ms
[2025-07-24 18:44:16,802] INFO django.request: GET /static/css/reset-quantity.css | Status: 500 | User: Anonymous | Duration: 3.46 ms
[2025-07-24 18:44:16,803] ERROR django.request: Internal Server Error: /static/css/reset-quantity.css
[2025-07-24 18:44:16,883] INFO django.request: GET /static/css/reset-quantity.css | Status: 500 | User: Anonymous | Duration: 3.04 ms
[2025-07-24 18:44:16,883] ERROR django.request: Internal Server Error: /static/css/reset-quantity.css
[2025-07-24 18:44:16,887] INFO django.request: GET /static/js/iconsLoad.js | Status: 500 | User: Anonymous | Duration: 2.22 ms
[2025-07-24 18:44:16,887] ERROR django.request: Internal Server Error: /static/js/iconsLoad.js
[2025-07-24 18:44:19,129] ERROR django.request: Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: django_site

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\sync.py", line 493, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\GitHub\CantinaShop\common\mixins.py", line 17, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\utils\decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\utils\decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\contrib\auth\views.py", line 89, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\views\generic\base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\views\generic\edit.py", line 142, in get
    return self.render_to_response(self.get_context_data())
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\contrib\auth\views.py", line 113, in get_context_data
    current_site = get_current_site(self.request)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\contrib\sites\shortcuts.py", line 16, in get_current_site
    return Site.objects.get_current(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\contrib\sites\models.py", line 59, in get_current
    return self._get_site_by_id(site_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\contrib\sites\models.py", line 30, in _get_site_by_id
    site = self.get(pk=site_id)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: django_site
[2025-07-24 18:44:19,136] INFO django.request: GET /accounts/login/ | Status: 500 | User: Anonymous | Duration: 8.46 ms
[2025-07-24 18:49:04,610] INFO django.request: GET / | Status: 200 | User: Anonymous | Duration: 54.57 ms
[2025-07-24 18:49:04,640] INFO django.request: GET /static/css/reset-quantity.css | Status: 500 | User: Anonymous | Duration: 3.17 ms
[2025-07-24 18:49:04,641] ERROR django.request: Internal Server Error: /static/css/reset-quantity.css
[2025-07-24 18:49:04,645] INFO django.request: GET /static/js/iconsLoad.js | Status: 500 | User: Anonymous | Duration: 2.02 ms
[2025-07-24 18:49:04,646] ERROR django.request: Internal Server Error: /static/js/iconsLoad.js
[2025-07-24 18:49:04,680] INFO django.request: GET /static/css/reset-quantity.css | Status: 500 | User: Anonymous | Duration: 2.00 ms
[2025-07-24 18:49:04,680] ERROR django.request: Internal Server Error: /static/css/reset-quantity.css
[2025-07-24 18:49:05,990] ERROR django.request: Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: django_site

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\sync.py", line 493, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\GitHub\CantinaShop\common\mixins.py", line 17, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\utils\decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\utils\decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\contrib\auth\views.py", line 89, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\views\generic\base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\views\generic\edit.py", line 142, in get
    return self.render_to_response(self.get_context_data())
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\contrib\auth\views.py", line 113, in get_context_data
    current_site = get_current_site(self.request)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\contrib\sites\shortcuts.py", line 16, in get_current_site
    return Site.objects.get_current(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\contrib\sites\models.py", line 59, in get_current
    return self._get_site_by_id(site_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\contrib\sites\models.py", line 30, in _get_site_by_id
    site = self.get(pk=site_id)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: django_site
[2025-07-24 18:49:05,995] INFO django.request: GET /accounts/login/ | Status: 500 | User: Anonymous | Duration: 9.28 ms
[2025-07-24 18:51:10,124] ERROR django.request: Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: django_site

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\sync.py", line 493, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\GitHub\CantinaShop\common\mixins.py", line 17, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\utils\decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\utils\decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\contrib\auth\views.py", line 89, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\views\generic\base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\views\generic\edit.py", line 142, in get
    return self.render_to_response(self.get_context_data())
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\contrib\auth\views.py", line 113, in get_context_data
    current_site = get_current_site(self.request)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\contrib\sites\shortcuts.py", line 16, in get_current_site
    return Site.objects.get_current(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\contrib\sites\models.py", line 59, in get_current
    return self._get_site_by_id(site_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\contrib\sites\models.py", line 30, in _get_site_by_id
    site = self.get(pk=site_id)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: django_site
[2025-07-24 18:51:10,129] INFO django.request: GET /accounts/login/ | Status: 500 | User: Anonymous | Duration: 51.01 ms
[2025-07-24 18:51:30,441] ERROR django.request: Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: django_site

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\sync.py", line 493, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\GitHub\CantinaShop\common\mixins.py", line 17, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\utils\decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\utils\decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\contrib\auth\views.py", line 89, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\views\generic\base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\views\generic\edit.py", line 142, in get
    return self.render_to_response(self.get_context_data())
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\contrib\auth\views.py", line 113, in get_context_data
    current_site = get_current_site(self.request)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\contrib\sites\shortcuts.py", line 16, in get_current_site
    return Site.objects.get_current(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\contrib\sites\models.py", line 59, in get_current
    return self._get_site_by_id(site_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\contrib\sites\models.py", line 30, in _get_site_by_id
    site = self.get(pk=site_id)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: django_site
[2025-07-24 18:51:30,447] INFO django.request: GET /accounts/login/ | Status: 500 | User: Anonymous | Duration: 72.30 ms
[2025-07-24 18:51:42,901] INFO django.request: GET /accounts/login/ | Status: 200 | User: Anonymous | Duration: 57.32 ms
[2025-07-24 18:51:44,734] INFO django.request: GET /accounts/register/ | Status: 200 | User: Anonymous | Duration: 5.06 ms
[2025-07-24 18:51:51,658] INFO django.request: POST /accounts/register/ | Status: 302 | User: Anonymous | Duration: 1678.22 ms
[2025-07-24 18:51:51,665] INFO django.request: GET /accounts/email-confirmation-sent/ | Status: 200 | User: Anonymous | Duration: 3.08 ms
[2025-07-24 18:51:54,037] INFO django.request: GET /accounts/activate/MQ/ctgkee-44fa4c30f54355224c3e9d5a382575d2/ | Status: 302 | User: DimitarKiuliumov | Duration: 25.34 ms
[2025-07-24 18:51:54,046] INFO django.request: GET /accounts/activation-success/ | Status: 200 | User: DimitarKiuliumov | Duration: 3.43 ms
[2025-07-24 18:51:57,006] INFO django.request: GET / | Status: 200 | User: DimitarKiuliumov | Duration: 9.38 ms
[2025-07-24 18:51:58,589] INFO django.request: GET /products/cart/ | Status: 200 | User: DimitarKiuliumov | Duration: 6.43 ms
[2025-07-24 18:51:59,485] INFO django.request: GET /accounts/ | Status: 200 | User: DimitarKiuliumov | Duration: 9.54 ms
[2025-07-24 18:52:05,158] INFO django.request: GET /products/ | Status: 200 | User: DimitarKiuliumov | Duration: 5.48 ms
[2025-07-24 18:52:06,136] INFO django.request: GET /api/messages/1/ | Status: 200 | User: DimitarKiuliumov | Duration: 9.80 ms
[2025-07-24 18:52:07,993] INFO django.request: GET /accounts/ | Status: 200 | User: DimitarKiuliumov | Duration: 7.41 ms
[2025-07-24 18:52:10,964] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 404 | User: DimitarKiuliumov | Duration: 2.39 ms
[2025-07-24 18:52:10,969] WARNING django.request: Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 18:52:17,024] INFO django.request: GET /accounts/ | Status: 200 | User: DimitarKiuliumov | Duration: 8.88 ms
[2025-07-24 18:52:18,557] INFO django.request: GET / | Status: 200 | User: DimitarKiuliumov | Duration: 6.66 ms
[2025-07-24 18:52:19,389] INFO django.request: GET /api/messages/1/ | Status: 200 | User: DimitarKiuliumov | Duration: 6.09 ms
[2025-07-24 18:52:24,561] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 404 | User: DimitarKiuliumov | Duration: 5.04 ms
[2025-07-24 18:52:24,562] WARNING django.request: Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 18:52:41,419] INFO django.request: GET / | Status: 200 | User: DimitarKiuliumov | Duration: 6.44 ms
[2025-07-24 18:52:42,679] INFO django.request: GET /api/messages/1/ | Status: 200 | User: DimitarKiuliumov | Duration: 5.04 ms
[2025-07-24 18:52:45,274] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 404 | User: DimitarKiuliumov | Duration: 10.55 ms
[2025-07-24 18:52:45,275] WARNING django.request: Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 18:54:33,827] INFO django.request: GET / | Status: 200 | User: DimitarKiuliumov | Duration: 59.73 ms
[2025-07-24 18:54:33,865] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 404 | User: DimitarKiuliumov | Duration: 5.51 ms
[2025-07-24 18:54:33,866] WARNING django.request: Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 18:54:34,894] INFO django.request: GET /api/messages/1/ | Status: 200 | User: DimitarKiuliumov | Duration: 6.18 ms
[2025-07-24 18:54:40,209] INFO django.request: GET /products/?category=Bracelets | Status: 200 | User: DimitarKiuliumov | Duration: 8.82 ms
[2025-07-24 18:54:40,242] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 404 | User: DimitarKiuliumov | Duration: 5.85 ms
[2025-07-24 18:54:40,242] WARNING django.request: Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 18:54:41,715] INFO django.request: GET /api/messages/1/ | Status: 200 | User: DimitarKiuliumov | Duration: 6.18 ms
[2025-07-24 18:54:43,248] INFO django.request: GET /products/cart/ | Status: 200 | User: DimitarKiuliumov | Duration: 3.49 ms
[2025-07-24 18:54:43,282] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 404 | User: DimitarKiuliumov | Duration: 4.61 ms
[2025-07-24 18:54:43,283] WARNING django.request: Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 18:54:44,202] INFO django.request: GET /api/messages/1/ | Status: 200 | User: DimitarKiuliumov | Duration: 6.10 ms
[2025-07-24 18:54:46,182] INFO django.request: GET /accounts/ | Status: 200 | User: DimitarKiuliumov | Duration: 11.45 ms
[2025-07-24 18:54:46,213] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 404 | User: DimitarKiuliumov | Duration: 4.50 ms
[2025-07-24 18:54:46,213] WARNING django.request: Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 18:55:10,586] INFO django.request: GET /products/cart/ | Status: 200 | User: DimitarKiuliumov | Duration: 5.03 ms
[2025-07-24 18:55:11,409] INFO django.request: GET /api/messages/1/ | Status: 200 | User: DimitarKiuliumov | Duration: 6.20 ms
[2025-07-24 18:55:45,407] INFO django.request: GET /products/cart/ | Status: 200 | User: DimitarKiuliumov | Duration: 10.32 ms
[2025-07-24 18:55:46,393] INFO django.request: GET /chat/admin/ | Status: 200 | User: DimitarKiuliumov | Duration: 4.84 ms
[2025-07-24 18:55:48,565] INFO django.request: GET / | Status: 200 | User: DimitarKiuliumov | Duration: 5.29 ms
[2025-07-24 18:55:57,286] INFO django.request: POST /accounts/logout/ | Status: 302 | User: Anonymous | Duration: 7.23 ms
[2025-07-24 18:55:57,293] INFO django.request: GET / | Status: 200 | User: Anonymous | Duration: 3.36 ms
[2025-07-24 18:55:57,782] INFO django.request: GET /accounts/login/ | Status: 200 | User: Anonymous | Duration: 6.05 ms
[2025-07-24 18:55:59,300] INFO django.request: GET /accounts/register/ | Status: 200 | User: Anonymous | Duration: 4.02 ms
[2025-07-24 18:56:16,159] INFO django.request: POST /accounts/register/ | Status: 302 | User: Anonymous | Duration: 1668.92 ms
[2025-07-24 18:56:16,168] INFO django.request: GET /accounts/email-confirmation-sent/ | Status: 200 | User: Anonymous | Duration: 0.00 ms
[2025-07-24 18:56:19,090] INFO django.request: GET /accounts/activate/Mg/ctgklq-a440e24e16ec6bd9fe7c643638f60380/ | Status: 302 | User: IvanGoshov | Duration: 25.31 ms
[2025-07-24 18:56:19,101] INFO django.request: GET /accounts/activation-success/ | Status: 200 | User: IvanGoshov | Duration: 0.00 ms
[2025-07-24 18:56:21,046] INFO django.request: GET / | Status: 200 | User: IvanGoshov | Duration: 4.89 ms
[2025-07-24 18:56:22,737] INFO django.request: GET /api/messages/2/ | Status: 200 | User: IvanGoshov | Duration: 6.32 ms
[2025-07-24 18:56:28,265] INFO django.request: GET /accounts/ | Status: 200 | User: IvanGoshov | Duration: 7.64 ms
[2025-07-24 18:56:31,686] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 404 | User: IvanGoshov | Duration: 4.41 ms
[2025-07-24 18:56:31,687] WARNING django.request: Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 18:56:54,846] INFO django.request: GET /products/ | Status: 200 | User: IvanGoshov | Duration: 6.03 ms
[2025-07-24 18:56:56,010] INFO django.request: POST /accounts/logout/ | Status: 302 | User: Anonymous | Duration: 7.36 ms
[2025-07-24 18:56:56,017] INFO django.request: GET / | Status: 200 | User: Anonymous | Duration: 3.30 ms
[2025-07-24 18:56:56,536] INFO django.request: GET /accounts/login/ | Status: 200 | User: Anonymous | Duration: 4.20 ms
[2025-07-24 18:56:58,733] INFO django.request: POST /accounts/login/ | Status: 302 | User: DimitarKiuliumov | Duration: 350.26 ms
[2025-07-24 18:56:58,741] INFO django.request: GET / | Status: 200 | User: DimitarKiuliumov | Duration: 5.12 ms
[2025-07-24 18:57:00,437] INFO django.request: GET /admin/accounts/usermodel/ | Status: 200 | User: DimitarKiuliumov | Duration: 24.73 ms
[2025-07-24 18:57:00,483] INFO django.request: GET /admin/jsi18n/ | Status: 200 | User: DimitarKiuliumov | Duration: 15.40 ms
[2025-07-24 18:57:03,286] INFO django.request: GET /products/ | Status: 200 | User: DimitarKiuliumov | Duration: 7.10 ms
[2025-07-24 18:57:03,819] INFO django.request: GET /products/category/create/ | Status: 200 | User: DimitarKiuliumov | Duration: 6.10 ms
[2025-07-24 18:57:05,578] INFO django.request: POST /products/category/create/ | Status: 302 | User: DimitarKiuliumov | Duration: 21.23 ms
[2025-07-24 18:57:05,586] INFO django.request: GET /products/ | Status: 200 | User: DimitarKiuliumov | Duration: 6.22 ms
[2025-07-24 18:57:06,823] INFO django.request: GET /products/new/ | Status: 200 | User: DimitarKiuliumov | Duration: 9.56 ms
[2025-07-24 18:57:17,228] INFO django.request: POST /products/new/ | Status: 302 | User: DimitarKiuliumov | Duration: 1462.88 ms
[2025-07-24 18:57:17,245] INFO django.request: GET /products/details/test/ | Status: 200 | User: DimitarKiuliumov | Duration: 12.92 ms
[2025-07-24 18:57:22,327] INFO django.request: POST /products/rate/test | Status: 302 | User: DimitarKiuliumov | Duration: 10.15 ms
[2025-07-24 18:57:22,337] INFO django.request: GET /products/details/test/ | Status: 200 | User: DimitarKiuliumov | Duration: 8.26 ms
[2025-07-24 18:57:23,680] INFO django.request: GET /products/edit/test/ | Status: 200 | User: DimitarKiuliumov | Duration: 8.24 ms
[2025-07-24 18:57:24,768] INFO django.request: GET /chat/admin/ | Status: 200 | User: DimitarKiuliumov | Duration: 5.52 ms
[2025-07-24 18:57:28,148] INFO django.request: GET /accounts/ | Status: 200 | User: DimitarKiuliumov | Duration: 8.42 ms
[2025-07-24 18:59:12,581] INFO django.request: GET /products/ | Status: 200 | User: DimitarKiuliumov | Duration: 7.08 ms
[2025-07-24 18:59:13,749] INFO django.request: GET /chat/admin/ | Status: 200 | User: DimitarKiuliumov | Duration: 7.65 ms
[2025-07-24 18:59:15,629] INFO django.request: GET /products/details/test/ | Status: 200 | User: DimitarKiuliumov | Duration: 9.02 ms
[2025-07-24 18:59:17,208] INFO django.request: GET /chat/admin/ | Status: 200 | User: DimitarKiuliumov | Duration: 4.45 ms
[2025-07-24 18:59:19,112] INFO django.request: GET /products/edit/test/ | Status: 200 | User: DimitarKiuliumov | Duration: 6.78 ms
[2025-07-24 18:59:23,451] INFO django.request: POST /products/edit/test/ | Status: 302 | User: DimitarKiuliumov | Duration: 949.89 ms
[2025-07-24 18:59:23,465] INFO django.request: GET /products/details/test/ | Status: 200 | User: DimitarKiuliumov | Duration: 10.41 ms
[2025-07-24 18:59:26,014] INFO django.request: GET /chat/admin/ | Status: 200 | User: DimitarKiuliumov | Duration: 5.01 ms
[2025-07-24 18:59:30,236] INFO django.request: GET /products/edit/test/ | Status: 200 | User: DimitarKiuliumov | Duration: 7.18 ms
[2025-07-24 18:59:31,671] INFO django.request: POST /products/edit/test/ | Status: 302 | User: DimitarKiuliumov | Duration: 360.97 ms
[2025-07-24 18:59:31,686] INFO django.request: GET /products/details/test/ | Status: 200 | User: DimitarKiuliumov | Duration: 12.27 ms
[2025-07-24 18:59:33,736] INFO django.request: POST /products/details/test/ | Status: 200 | User: DimitarKiuliumov | Duration: 27.67 ms
[2025-07-24 18:59:35,470] INFO django.request: GET /chat/admin/ | Status: 200 | User: DimitarKiuliumov | Duration: 5.81 ms
[2025-07-24 19:00:01,873] INFO django.request: GET /accounts/ | Status: 200 | User: DimitarKiuliumov | Duration: 9.03 ms
[2025-07-24 19:00:03,132] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 404 | User: DimitarKiuliumov | Duration: 5.67 ms
[2025-07-24 19:00:03,132] WARNING django.request: Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:00:33,093] INFO django.request: GET / | Status: 200 | User: DimitarKiuliumov | Duration: 5.79 ms
[2025-07-24 19:00:33,129] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 404 | User: DimitarKiuliumov | Duration: 10.81 ms
[2025-07-24 19:00:33,129] WARNING django.request: Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:00:36,023] INFO django.request: GET /chat/admin/ | Status: 200 | User: DimitarKiuliumov | Duration: 1.58 ms
[2025-07-24 19:00:36,055] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 404 | User: DimitarKiuliumov | Duration: 7.22 ms
[2025-07-24 19:00:36,056] WARNING django.request: Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:00:59,378] INFO django.request: GET / | Status: 200 | User: DimitarKiuliumov | Duration: 3.63 ms
[2025-07-24 19:00:59,398] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 404 | User: DimitarKiuliumov | Duration: 4.17 ms
[2025-07-24 19:00:59,398] WARNING django.request: Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:01:00,983] INFO django.request: GET /accounts/ | Status: 200 | User: DimitarKiuliumov | Duration: 7.06 ms
[2025-07-24 19:01:01,015] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 404 | User: DimitarKiuliumov | Duration: 11.61 ms
[2025-07-24 19:01:01,015] WARNING django.request: Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:01:25,402] INFO django.request: GET /accounts/ | Status: 200 | User: DimitarKiuliumov | Duration: 67.23 ms
[2025-07-24 19:01:25,424] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 404 | User: DimitarKiuliumov | Duration: 5.04 ms
[2025-07-24 19:01:25,424] WARNING django.request: Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:01:34,289] INFO django.request: GET / | Status: 200 | User: DimitarKiuliumov | Duration: 5.39 ms
[2025-07-24 19:01:34,312] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 404 | User: DimitarKiuliumov | Duration: 4.26 ms
[2025-07-24 19:01:34,314] WARNING django.request: Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:01:36,511] INFO django.request: GET /chat/admin/ | Status: 200 | User: DimitarKiuliumov | Duration: 5.55 ms
[2025-07-24 19:01:36,563] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 404 | User: DimitarKiuliumov | Duration: 8.81 ms
[2025-07-24 19:01:36,563] WARNING django.request: Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:01:37,760] INFO django.request: GET / | Status: 200 | User: DimitarKiuliumov | Duration: 4.68 ms
[2025-07-24 19:01:37,783] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 404 | User: DimitarKiuliumov | Duration: 5.45 ms
[2025-07-24 19:01:37,784] WARNING django.request: Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:01:39,156] INFO django.request: GET /products/ | Status: 200 | User: DimitarKiuliumov | Duration: 8.80 ms
[2025-07-24 19:01:39,174] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 404 | User: DimitarKiuliumov | Duration: 5.55 ms
[2025-07-24 19:01:39,176] WARNING django.request: Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:01:42,615] INFO django.request: GET /accounts/ | Status: 200 | User: DimitarKiuliumov | Duration: 8.03 ms
[2025-07-24 19:01:42,639] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 404 | User: DimitarKiuliumov | Duration: 7.13 ms
[2025-07-24 19:01:42,640] WARNING django.request: Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:02:12,679] INFO django.request: GET /accounts/ | Status: 200 | User: DimitarKiuliumov | Duration: 93.88 ms
[2025-07-24 19:02:12,709] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 404 | User: DimitarKiuliumov | Duration: 6.62 ms
[2025-07-24 19:02:12,710] WARNING django.request: Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:02:13,209] INFO django.request: GET /chat/admin/ | Status: 200 | User: DimitarKiuliumov | Duration: 7.50 ms
[2025-07-24 19:02:13,261] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 404 | User: DimitarKiuliumov | Duration: 7.38 ms
[2025-07-24 19:02:13,261] WARNING django.request: Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:02:14,468] INFO django.request: GET / | Status: 200 | User: DimitarKiuliumov | Duration: 6.05 ms
[2025-07-24 19:02:14,492] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 404 | User: DimitarKiuliumov | Duration: 7.64 ms
[2025-07-24 19:02:14,493] WARNING django.request: Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:02:15,184] INFO django.request: GET / | Status: 200 | User: DimitarKiuliumov | Duration: 5.20 ms
[2025-07-24 19:02:15,213] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 404 | User: DimitarKiuliumov | Duration: 8.73 ms
[2025-07-24 19:02:15,213] WARNING django.request: Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:02:18,553] INFO django.request: GET /products/ | Status: 200 | User: DimitarKiuliumov | Duration: 10.40 ms
[2025-07-24 19:02:18,582] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 404 | User: DimitarKiuliumov | Duration: 9.93 ms
[2025-07-24 19:02:18,583] WARNING django.request: Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:02:19,517] INFO django.request: GET / | Status: 200 | User: DimitarKiuliumov | Duration: 4.10 ms
[2025-07-24 19:02:19,569] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 404 | User: DimitarKiuliumov | Duration: 12.65 ms
[2025-07-24 19:02:19,570] WARNING django.request: Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:02:21,757] INFO django.request: GET /products/ | Status: 200 | User: DimitarKiuliumov | Duration: 7.15 ms
[2025-07-24 19:02:23,307] INFO django.request: GET /products/details/test/ | Status: 200 | User: DimitarKiuliumov | Duration: 15.19 ms
[2025-07-24 19:02:24,632] INFO django.request: GET /products/edit/test/ | Status: 200 | User: DimitarKiuliumov | Duration: 9.89 ms
[2025-07-24 19:13:37,772] INFO django.request: GET /accounts/login/ | Status: 302 | User: DimitarKiuliumov | Duration: 48.70 ms
[2025-07-24 19:13:43,064] INFO django.request: GET /products/edit/test/ | Status: 200 | User: DimitarKiuliumov | Duration: 67.83 ms
[2025-07-24 19:13:43,088] INFO django.request: GET /static/css/reset-quantity.css | Status: 500 | User: DimitarKiuliumov | Duration: 3.10 ms
[2025-07-24 19:13:43,088] ERROR django.request: Internal Server Error: /static/css/reset-quantity.css
[2025-07-24 19:13:43,094] INFO django.request: GET /static/js/iconsLoad.js | Status: 500 | User: DimitarKiuliumov | Duration: 2.05 ms
[2025-07-24 19:13:43,094] ERROR django.request: Internal Server Error: /static/js/iconsLoad.js
[2025-07-24 19:13:43,098] INFO django.request: GET /static/js/chatFrontEnd.js | Status: 500 | User: DimitarKiuliumov | Duration: 2.01 ms
[2025-07-24 19:13:43,099] ERROR django.request: Internal Server Error: /static/js/chatFrontEnd.js
[2025-07-24 19:13:44,450] INFO django.request: GET /products/ | Status: 200 | User: DimitarKiuliumov | Duration: 8.65 ms
[2025-07-24 19:13:44,503] INFO django.request: GET /static/css/reset-quantity.css | Status: 500 | User: DimitarKiuliumov | Duration: 27.28 ms
[2025-07-24 19:13:44,504] INFO django.request: GET /static/js/createPopUp.js | Status: 500 | User: DimitarKiuliumov | Duration: 27.28 ms
[2025-07-24 19:13:44,505] INFO django.request: GET /static/js/iconsLoad.js | Status: 500 | User: DimitarKiuliumov | Duration: 26.28 ms
[2025-07-24 19:13:44,505] INFO django.request: GET /static/js/chatFrontEnd.js | Status: 500 | User: DimitarKiuliumov | Duration: 28.28 ms
[2025-07-24 19:13:44,505] ERROR django.request: Internal Server Error: /static/css/reset-quantity.css
[2025-07-24 19:13:44,505] ERROR django.request: Internal Server Error: /static/js/createPopUp.js
[2025-07-24 19:13:44,506] ERROR django.request: Internal Server Error: /static/js/chatFrontEnd.js
[2025-07-24 19:13:44,506] ERROR django.request: Internal Server Error: /static/js/iconsLoad.js
[2025-07-24 19:13:45,889] INFO django.request: GET / | Status: 200 | User: DimitarKiuliumov | Duration: 6.07 ms
[2025-07-24 19:13:45,918] INFO django.request: GET /static/css/reset-quantity.css | Status: 500 | User: DimitarKiuliumov | Duration: 7.11 ms
[2025-07-24 19:13:45,919] ERROR django.request: Internal Server Error: /static/css/reset-quantity.css
[2025-07-24 19:13:45,919] INFO django.request: GET /static/js/iconsLoad.js | Status: 500 | User: DimitarKiuliumov | Duration: 6.04 ms
[2025-07-24 19:13:45,919] INFO django.request: GET /static/js/chatFrontEnd.js | Status: 500 | User: DimitarKiuliumov | Duration: 7.05 ms
[2025-07-24 19:13:45,920] ERROR django.request: Internal Server Error: /static/js/iconsLoad.js
[2025-07-24 19:13:45,922] ERROR django.request: Internal Server Error: /static/js/chatFrontEnd.js
[2025-07-24 19:13:49,403] INFO django.request: GET /products/ | Status: 200 | User: DimitarKiuliumov | Duration: 6.56 ms
[2025-07-24 19:13:49,426] INFO django.request: GET /static/css/reset-quantity.css | Status: 500 | User: DimitarKiuliumov | Duration: 2.01 ms
[2025-07-24 19:13:49,427] ERROR django.request: Internal Server Error: /static/css/reset-quantity.css
[2025-07-24 19:13:49,432] INFO django.request: GET /static/js/iconsLoad.js | Status: 500 | User: DimitarKiuliumov | Duration: 2.04 ms
[2025-07-24 19:13:49,432] ERROR django.request: Internal Server Error: /static/js/iconsLoad.js
[2025-07-24 19:13:49,438] INFO django.request: GET /static/js/chatFrontEnd.js | Status: 500 | User: DimitarKiuliumov | Duration: 2.00 ms
[2025-07-24 19:13:49,439] ERROR django.request: Internal Server Error: /static/js/chatFrontEnd.js
[2025-07-24 19:13:49,444] INFO django.request: GET /static/js/createPopUp.js | Status: 500 | User: DimitarKiuliumov | Duration: 2.07 ms
[2025-07-24 19:13:49,444] ERROR django.request: Internal Server Error: /static/js/createPopUp.js
[2025-07-24 19:13:50,943] INFO django.request: GET /products/details/test/ | Status: 200 | User: DimitarKiuliumov | Duration: 14.82 ms
[2025-07-24 19:13:50,981] INFO django.request: GET /static/js/toggleEdit.js | Status: 500 | User: DimitarKiuliumov | Duration: 9.30 ms
[2025-07-24 19:13:50,981] INFO django.request: GET /static/images/avatar.png | Status: 500 | User: DimitarKiuliumov | Duration: 8.29 ms
[2025-07-24 19:13:50,981] INFO django.request: GET /static/css/reset-quantity.css | Status: 500 | User: DimitarKiuliumov | Duration: 9.30 ms
[2025-07-24 19:13:50,982] INFO django.request: GET /static/js/chatFrontEnd.js | Status: 500 | User: DimitarKiuliumov | Duration: 9.30 ms
[2025-07-24 19:13:50,982] INFO django.request: GET /static/js/iconsLoad.js | Status: 500 | User: DimitarKiuliumov | Duration: 9.30 ms
[2025-07-24 19:13:50,983] ERROR django.request: Internal Server Error: /static/js/toggleEdit.js
[2025-07-24 19:13:50,983] ERROR django.request: Internal Server Error: /static/images/avatar.png
[2025-07-24 19:13:50,983] ERROR django.request: Internal Server Error: /static/css/reset-quantity.css
[2025-07-24 19:13:50,983] ERROR django.request: Internal Server Error: /static/js/chatFrontEnd.js
[2025-07-24 19:13:50,984] ERROR django.request: Internal Server Error: /static/js/iconsLoad.js
[2025-07-24 19:13:51,001] INFO django.request: GET /static/js/confirmDelete.js | Status: 500 | User: DimitarKiuliumov | Duration: 8.13 ms
[2025-07-24 19:13:51,003] INFO django.request: GET /static/js/quantityButtonPlus.js | Status: 500 | User: DimitarKiuliumov | Duration: 8.13 ms
[2025-07-24 19:13:51,003] ERROR django.request: Internal Server Error: /static/js/confirmDelete.js
[2025-07-24 19:13:51,003] INFO django.request: GET /static/js/orderCookieQuantity.js | Status: 500 | User: DimitarKiuliumov | Duration: 9.04 ms
[2025-07-24 19:13:51,005] INFO django.request: GET /static/js/starRating.js | Status: 500 | User: DimitarKiuliumov | Duration: 10.14 ms
[2025-07-24 19:13:51,006] INFO django.request: GET /static/js/orderPopUp.js | Status: 500 | User: DimitarKiuliumov | Duration: 9.14 ms
[2025-07-24 19:13:51,007] ERROR django.request: Internal Server Error: /static/js/quantityButtonPlus.js
[2025-07-24 19:13:51,007] ERROR django.request: Internal Server Error: /static/js/orderCookieQuantity.js
[2025-07-24 19:13:51,007] ERROR django.request: Internal Server Error: /static/js/starRating.js
[2025-07-24 19:13:51,008] ERROR django.request: Internal Server Error: /static/js/orderPopUp.js
[2025-07-24 19:13:51,014] INFO django.request: GET /static/js/createPopUp.js | Status: 500 | User: DimitarKiuliumov | Duration: 4.03 ms
[2025-07-24 19:13:51,015] ERROR django.request: Internal Server Error: /static/js/createPopUp.js
[2025-07-24 19:13:54,000] INFO django.request: GET /products/details/test3ert | Status: 500 | User: DimitarKiuliumov | Duration: 3.01 ms
[2025-07-24 19:13:54,001] ERROR django.request: Internal Server Error: /products/details/test3ert
[2025-07-24 19:13:54,025] INFO django.request: GET /favicon.ico | Status: 500 | User: DimitarKiuliumov | Duration: 3.16 ms
[2025-07-24 19:13:54,026] ERROR django.request: Internal Server Error: /favicon.ico
[2025-07-24 19:14:07,010] INFO django.request: GET /products/details/test3ert | Status: 301 | User: DimitarKiuliumov | Duration: 40.42 ms
[2025-07-24 19:14:07,019] INFO django.request: GET /products/details/test3ert/ | Status: 404 | User: DimitarKiuliumov | Duration: 5.69 ms
[2025-07-24 19:14:07,019] WARNING django.request: Not Found: /products/details/test3ert/
[2025-07-24 19:14:07,041] INFO django.request: GET /favicon.ico | Status: 404 | User: DimitarKiuliumov | Duration: 5.04 ms
[2025-07-24 19:14:07,042] WARNING django.request: Not Found: /favicon.ico
[2025-07-24 19:15:16,843] INFO django.request: GET /products/details/test3ert/ | Status: 404 | User: DimitarKiuliumov | Duration: 43.55 ms
[2025-07-24 19:15:16,844] WARNING django.request: Not Found: /products/details/test3ert/
[2025-07-24 19:15:26,485] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 55.12 ms
[2025-07-24 19:15:26,486] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:15:27,001] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 3.43 ms
[2025-07-24 19:15:27,001] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:15:27,153] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 3.22 ms
[2025-07-24 19:15:27,154] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:15:27,284] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 3.08 ms
[2025-07-24 19:15:27,285] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:15:27,435] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 3.13 ms
[2025-07-24 19:15:27,436] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:15:27,575] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 4.10 ms
[2025-07-24 19:15:27,575] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:15:27,719] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 3.55 ms
[2025-07-24 19:15:27,719] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:15:30,187] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 2.16 ms
[2025-07-24 19:15:30,187] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:16:25,780] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 55.31 ms
[2025-07-24 19:16:25,781] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:16:25,801] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 3.15 ms
[2025-07-24 19:16:25,802] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:16:26,450] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 4.02 ms
[2025-07-24 19:16:26,450] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:16:26,464] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 3.12 ms
[2025-07-24 19:16:26,464] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:16:26,612] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 4.01 ms
[2025-07-24 19:16:26,613] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:16:26,625] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 3.23 ms
[2025-07-24 19:16:26,626] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:19:26,023] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 59.77 ms
[2025-07-24 19:19:26,024] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:19:26,047] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 2.01 ms
[2025-07-24 19:19:26,048] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:19:26,118] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 3.32 ms
[2025-07-24 19:19:26,119] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:19:26,132] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 3.80 ms
[2025-07-24 19:19:26,133] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:19:26,309] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 4.14 ms
[2025-07-24 19:19:26,309] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:19:26,329] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 3.03 ms
[2025-07-24 19:19:26,331] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:19:26,470] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 5.64 ms
[2025-07-24 19:19:26,471] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:19:26,493] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 3.19 ms
[2025-07-24 19:19:26,493] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:19:26,645] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 4.07 ms
[2025-07-24 19:19:26,645] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:19:26,664] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 2.50 ms
[2025-07-24 19:19:26,665] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:19:31,058] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 4.02 ms
[2025-07-24 19:19:31,058] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:19:31,072] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 2.08 ms
[2025-07-24 19:19:31,072] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:19:31,213] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 4.37 ms
[2025-07-24 19:19:31,213] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:19:31,226] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 2.18 ms
[2025-07-24 19:19:31,227] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:19:31,354] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 4.13 ms
[2025-07-24 19:19:31,354] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:19:31,367] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 3.04 ms
[2025-07-24 19:19:31,367] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:19:31,487] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 4.01 ms
[2025-07-24 19:19:31,487] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:19:31,501] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 3.02 ms
[2025-07-24 19:19:31,502] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:19:31,624] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 4.24 ms
[2025-07-24 19:19:31,624] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:19:31,638] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 3.25 ms
[2025-07-24 19:19:31,638] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:19:31,764] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 3.71 ms
[2025-07-24 19:19:31,764] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:19:31,780] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 2.37 ms
[2025-07-24 19:19:31,780] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:19:31,901] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 4.10 ms
[2025-07-24 19:19:31,902] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:19:31,916] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 3.34 ms
[2025-07-24 19:19:31,916] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:19:32,053] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 4.28 ms
[2025-07-24 19:19:32,054] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:19:32,068] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 2.02 ms
[2025-07-24 19:19:32,069] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:19:32,201] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 4.02 ms
[2025-07-24 19:19:32,202] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:19:32,215] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 2.67 ms
[2025-07-24 19:19:32,216] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:19:32,331] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 4.03 ms
[2025-07-24 19:19:32,331] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:19:32,344] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 2.13 ms
[2025-07-24 19:19:32,344] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:19:32,610] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 4.10 ms
[2025-07-24 19:19:32,611] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:19:32,623] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 2.01 ms
[2025-07-24 19:19:32,624] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:19:32,757] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 4.01 ms
[2025-07-24 19:19:32,757] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:19:32,771] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 2.01 ms
[2025-07-24 19:19:32,771] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:19:32,890] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 3.09 ms
[2025-07-24 19:19:32,891] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:19:32,903] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 2.01 ms
[2025-07-24 19:19:32,904] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:19:33,049] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 4.11 ms
[2025-07-24 19:19:33,050] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:19:33,063] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 2.00 ms
[2025-07-24 19:19:33,063] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:19:33,192] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 4.02 ms
[2025-07-24 19:19:33,192] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:19:33,205] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 3.26 ms
[2025-07-24 19:19:33,206] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:19:33,343] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 4.04 ms
[2025-07-24 19:19:33,344] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:19:33,358] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 3.32 ms
[2025-07-24 19:19:33,359] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:19:33,614] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 3.33 ms
[2025-07-24 19:19:33,614] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:19:33,627] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 2.00 ms
[2025-07-24 19:19:33,627] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:19:33,918] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 4.02 ms
[2025-07-24 19:19:33,918] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:19:33,931] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 2.18 ms
[2025-07-24 19:19:33,931] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:19:34,069] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 4.11 ms
[2025-07-24 19:19:34,070] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:19:34,082] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 2.01 ms
[2025-07-24 19:19:34,082] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:19:34,225] INFO django.request: GET /products/details/test3ert/ | Status: 500 | User: DimitarKiuliumov | Duration: 4.36 ms
[2025-07-24 19:19:34,226] ERROR django.request: Internal Server Error: /products/details/test3ert/
[2025-07-24 19:19:34,239] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 2.18 ms
[2025-07-24 19:19:34,239] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:22:44,923] INFO django.request: GET /api/404 | Status: 500 | User: DimitarKiuliumov | Duration: 54.91 ms
[2025-07-24 19:22:44,924] ERROR django.request: Internal Server Error: /api/404
[2025-07-24 19:22:44,946] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 500 | User: DimitarKiuliumov | Duration: 2.35 ms
[2025-07-24 19:22:44,946] ERROR django.request: Internal Server Error: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:24:11,454] INFO django.request: GET /api/404 | Status: 404 | User: DimitarKiuliumov | Duration: 53.38 ms
[2025-07-24 19:24:11,455] WARNING django.request: Not Found: /api/404
[2025-07-24 19:24:11,475] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 404 | User: DimitarKiuliumov | Duration: 3.04 ms
[2025-07-24 19:24:11,476] WARNING django.request: Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:24:11,677] INFO django.request: GET /api/404 | Status: 404 | User: DimitarKiuliumov | Duration: 3.11 ms
[2025-07-24 19:24:11,677] WARNING django.request: Not Found: /api/404
[2025-07-24 19:24:11,692] INFO django.request: GET /.well-known/appspecific/com.chrome.devtools.json | Status: 404 | User: DimitarKiuliumov | Duration: 3.06 ms
[2025-07-24 19:24:11,693] WARNING django.request: Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-07-24 19:24:13,732] INFO django.request: GET / | Status: 200 | User: DimitarKiuliumov | Duration: 14.63 ms
[2025-07-24 19:24:15,334] INFO django.request: GET /accounts/ | Status: 200 | User: DimitarKiuliumov | Duration: 11.67 ms
[2025-07-24 19:24:18,276] INFO django.request: GET /products/ | Status: 200 | User: DimitarKiuliumov | Duration: 9.11 ms
[2025-07-24 19:24:20,095] INFO django.request: GET /products/details/test/ | Status: 200 | User: DimitarKiuliumov | Duration: 14.17 ms
[2025-07-24 19:24:25,310] INFO django.request: GET /products/ | Status: 200 | User: DimitarKiuliumov | Duration: 7.06 ms
[2025-07-24 19:24:25,738] INFO django.request: GET / | Status: 200 | User: DimitarKiuliumov | Duration: 6.10 ms
[2025-07-24 19:24:27,202] INFO django.request: GET /accounts/ | Status: 200 | User: DimitarKiuliumov | Duration: 7.04 ms
[2025-07-24 19:24:29,837] INFO django.request: GET /products/cart/ | Status: 200 | User: DimitarKiuliumov | Duration: 6.93 ms
[2025-07-24 19:24:34,014] INFO django.request: GET /products/ | Status: 200 | User: DimitarKiuliumov | Duration: 6.29 ms
[2025-07-24 19:24:34,922] INFO django.request: GET /products/new/ | Status: 200 | User: DimitarKiuliumov | Duration: 11.23 ms
[2025-07-24 19:24:45,824] INFO django.request: POST /products/new/ | Status: 302 | User: DimitarKiuliumov | Duration: 1418.62 ms
[2025-07-24 19:24:45,838] INFO django.request: GET /products/details/test3456/ | Status: 200 | User: DimitarKiuliumov | Duration: 10.28 ms
[2025-07-24 19:24:47,614] INFO django.request: GET /orders/add-to-cart/test3456/?quantity=1 | Status: 302 | User: DimitarKiuliumov | Duration: 4.35 ms
[2025-07-24 19:24:47,626] INFO django.request: GET /products/details/test3456/ | Status: 200 | User: DimitarKiuliumov | Duration: 9.11 ms
[2025-07-24 19:24:50,029] INFO django.request: GET /products/cart/ | Status: 200 | User: DimitarKiuliumov | Duration: 6.47 ms
[2025-07-24 19:24:56,395] INFO django.request: GET /products/cart/ | Status: 200 | User: DimitarKiuliumov | Duration: 7.33 ms
[2025-07-24 19:24:57,661] INFO django.request: GET /products/ | Status: 200 | User: DimitarKiuliumov | Duration: 6.12 ms
[2025-07-24 19:26:18,097] INFO django.request: POST /accounts/logout/ | Status: 302 | User: Anonymous | Duration: 6.93 ms
[2025-07-24 19:26:18,103] INFO django.request: GET / | Status: 200 | User: Anonymous | Duration: 3.01 ms
[2025-07-24 19:26:22,441] WARNING django.request: Forbidden (Permission denied): /products/edit/test/
Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\sync.py", line 493, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 72, in dispatch
    return self.handle_no_permission()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\GitHub\CantinaShop\common\mixins.py", line 11, in handle_no_permission
    raise PermissionDenied
django.core.exceptions.PermissionDenied
[2025-07-24 19:26:22,444] INFO django.request: GET /products/edit/test/ | Status: 403 | User: Anonymous | Duration: 5.22 ms
[2025-07-24 19:26:28,080] INFO django.request: GET /products/chat/admin | Status: 404 | User: Anonymous | Duration: 2.38 ms
[2025-07-24 19:26:28,080] WARNING django.request: Not Found: /products/chat/admin
[2025-07-24 19:26:34,536] WARNING django.request: Forbidden (Permission denied): /chat/admin/
Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\asgiref\sync.py", line 493, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\CantinaShop\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 134, in dispatch
    return self.handle_no_permission()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\GitHub\CantinaShop\chat\views.py", line 17, in handle_no_permission
django.core.exceptions.PermissionDenied
[2025-07-24 19:26:34,537] INFO django.request: GET /chat/admin/ | Status: 403 | User: Anonymous | Duration: 3.01 ms
[2025-07-24 19:26:35,876] INFO django.request: GET / | Status: 200 | User: Anonymous | Duration: 3.00 ms
[2025-07-24 19:26:39,240] INFO django.request: GET /njfsdgnfdg | Status: 404 | User: Anonymous | Duration: 2.01 ms
[2025-07-24 19:26:39,241] WARNING django.request: Not Found: /njfsdgnfdg
[2025-07-24 19:26:47,573] INFO django.request: GET / | Status: 200 | User: Anonymous | Duration: 3.01 ms
